OnlineEdu.WebUI/Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.BannerDtos;
using OnlineEdu.WebUI.Helpers;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("[area]/[controller]/[action]/{id?}")]
	public class BannerController : Controller
	{
		private readonly HttpClient _client = HttpClientInstance.CreateClient();
		public async Task<IActionResult> Index()
		{
			var values = await _client.GetFromJsonAsync<List<ResultBannerDto>>("banners");
			return View(values);
		}

		public async Task<IActionResult> DeleteBanner(int id)
		{
			await _client.DeleteAsync($"banners/{id}");
			return RedirectToAction(nameof(Index));
		}
		
		public IActionResult CreateBanner()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CreateBanner(CreateBannerDto dto)
		{
			await _client.PostAsJsonAsync("banners", dto);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> UpdateBanner(int id)
		{
			var value = await _client.GetFromJsonAsync<UpdateBannerDto>($"banners/{id}");
			return View(value);
		}

		[HttpPost]
		public async Task<IActionResult> UpdateBanner(UpdateBannerDto dto)
		{
			await _client.PutAsJsonAsync("banners", dto);
			return RedirectToAction(nameof(Index));
		}
	}
}

OnlineEdu.WebUI/Areas/Admin/Views/Banner/CreateBanner.cshtml
@model CreateBannerDto
@{
	ViewData["Title"] = "Create Banner";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
	<label>Image Url</label>
	<input type="text" asp-for="ImageUrl" class="form-control" />
	<br />
	<label>Title</label>
	<input type="text" asp-for="Title" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Save</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/Banner/Index.cshtml
@model List<ResultBannerDto>

@{
    ViewData["Title"] = "Banner Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
	int count = 0;
}

<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>Title</th>
		<th></th>
	</tr>
	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>
			<td><img src="@item.ImageUrl" style="height:75px;width:75px" />@item.Title</td>
			<td>
				<a asp-action="DeleteBanner" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-danger">Delete</a>
				<a asp-action="UpdateBanner" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-info">Update</a>
			</td>
		</tr>
	}
</table>
<br />

<a asp-action="CreateBanner" asp-controller="Banner" asp-area="Admin" class="btn btn-outline-primary">Create New Banner</a>

OnlineEdu.WebUI/Areas/Admin/Views/Banner/UpdateBanner.cshtml
@model UpdateBannerDto

@{
    ViewData["Title"] = "Update Banner";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
	<input type="hidden" asp-for="BannerId" />
	<label>Image Url</label>
	<input type="text" asp-for="ImageUrl" class="form-control" />
	<br />
	<label>Title</label>
	<input type="text" asp-for="Title" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Save</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>