OnlineEdu.WebUI/Areas/Admin/Controllers/SocialMediaController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.SocialMediaDtos;
using OnlineEdu.WebUI.Helpers;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class SocialMediaController : Controller
    {


        private readonly HttpClient _client = HttpClientInstance.CreateClient();
        public async Task<IActionResult> Index()
        {
            var values = await _client.GetFromJsonAsync<List<ResultSocialMediaDto>>("socialMedias");
            return View(values);
        }

        public async Task<IActionResult> DeleteSocialMedia(int id)
        {
            await _client.DeleteAsync($"socialMedias/{id}");
            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateSocialMedia()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSocialMedia(CreateSocialMediaDto dto)
        {
            await _client.PostAsJsonAsync("socialMedias", dto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateSocialMedia(int id)
        {
            var value = await _client.GetFromJsonAsync<UpdateSocialMediaDto>($"socialMedias/{id}");
            return View(value);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSocialMedia(UpdateSocialMediaDto dto)
        {
            await _client.PutAsJsonAsync("socialMedias", dto);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/CreateSocialMedia.cshtml
@model CreateSocialMediaDto
@{
	ViewData["Title"] = "Create Social Media";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
	<label>Title</label>
	<input type="string" asp-for="Title" class="form-control" />
	<br />
	<label>Icon</label>
	<input type="string" asp-for="Icon" class="form-control" />
	<br />
	<label>Url to Social Media</label>
	<input type="string" asp-for="Url" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Save</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/Index.cshtml
@model List<ResultSocialMediaDto>
@{
    ViewData["Title"] = "Social Media Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{
	int count = 0;
}

<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>Link</th>
		<th>Title</th>
		<th></th>
	</tr>
	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>

			<td> <a href="@item.Url" target="_blank"> <i class="@item.Icon fa-2x"></i></a></td>
			<td>@item.Title</td>
			<td>
				<button onclick="deleteSocialMedia(@item.SocialMediaId)" class="btn btn-outline-danger">Delete </button>
				<a asp-action="UpdateSocialMedia" asp-controller="SocialMedia" asp-area="Admin" asp-route-id="@item.SocialMediaId" class="btn btn-outline-info">Update</a>
			</td>
		</tr>

	}
</table>
<br />

<a asp-action="CreateSocialMedia" asp-controller="SocialMedia" asp-area="Admin" class="btn btn-outline-primary">Create New SocialMedia</a>

<script>


	function deleteSocialMedia(id) {


		Swal.fire({
			title: "Are you sure?",
			text: "You won't be able to revert this!",
			icon: "warning",
			showCancelButton: true,
			confirmButtonColor: "#3085d6",
			cancelButtonColor: "#d33",
			confirmButtonText: "Yes, delete it!",
			cancelButtonText: "Cancel"
		}).then((result) => {
			if (result.isConfirmed) {
				window.location.href = "/Admin/SocialMedia/DeleteSocialMedia/" + id;
			}
		});

	}

</script>

OnlineEdu.WebUI/Areas/Admin/Views/SocialMedia/UpdateSocialMedia.cshtml
@model UpdateSocialMediaDto
@{
    ViewData["Title"] = "UpdateSocialMedia";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
	<input type="hidden" asp-for="SocialMediaId" />
	<label>Title</label>
	<input type="string" asp-for="Title" class="form-control" />
	<br />
	<label>Icon</label>
	<input type="string" asp-for="Icon" class="form-control" />
	<br />
	<label>Url to Social Media</label>
	<input type="string" asp-for="Url" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Update</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>