OnlineEdu.WebUI/Areas/Admin/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineEdu.WebUI.DTOs.CourseCategoryDtos;
using OnlineEdu.WebUI.DTOs.CourseDtos;
using OnlineEdu.WebUI.Helpers;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class CourseController : Controller
    {
        private readonly HttpClient _client = HttpClientInstance.CreateClient();
        public async Task CategoryDropdown()
        {
            var courseCategoryList = await _client.GetFromJsonAsync<List<ResultCourseCategoryDto>>("courseCategories");
            List<SelectListItem> courseCategories = (from x in courseCategoryList
                                                        select new SelectListItem
                                                        {
                                                            Text = x.Name,
                                                            Value = x.CourseCategoryId.ToString()
                                                        }
                                                     ).ToList();

            ViewBag.courseCategories = courseCategories;   
        }
        public async Task<IActionResult> Index()
        {
            var values = await _client.GetFromJsonAsync<List<ResultCourseDto>>("courses");
            return View(values);
        }

        public async Task<IActionResult> DeleteCourse(int id)
        {
            await _client.DeleteAsync($"courses/{id}");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> CreateCourse()
        {
            await CategoryDropdown();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCourse(CreateCourseDto dto)
        {
            await _client.PostAsJsonAsync("courses", dto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateCourse(int id)
        {
            await CategoryDropdown();
            var value = await _client.GetFromJsonAsync<UpdateCourseDto>($"courses/{id}");
            return View(value);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCourse(UpdateCourseDto dto)
        {
            await _client.PutAsJsonAsync("courses", dto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ShowOnMainPage(int id)
        {
            await _client.GetAsync("courses/ShowOnMainPage/" + id);
            return RedirectToAction("Index");
        }
    }
}

OnlineEdu.WebUI/Areas/Admin/Views/Course/CreateCourse.cshtml
@model CreateCourseDto
@{
    ViewData["Title"] = "Create Course";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <label>ImageUrl</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Course Name</label>
    <input type="text" asp-for="CourseName" class="form-control" />
    <br />
    <label>Price</label>
    <input type="text" asp-for="Price" class="form-control" />
    <br />
    <label>Category</label>
    <select asp-for="CourseCategoryId" class="form-control" asp-items="@ViewBag.courseCategories">
        <option>Choose Category</option>
    </select>
    <br />
    <label>Show in main page?</label>
    <input type="checkbox" asp-for="IsShown" class="form-check" />
    <br />
    <button class="btn btn-outline-primary">Save</button>
    <button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/Course/Index.cshtml
@model List<ResultCourseDto>
@{
    ViewData["Title"] = "Courses";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
	int count = 0;
}

<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>ImageUrl</th>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
		<th>Main Page Status</th>
		<th></th>
		<th>Change Status</th>
	</tr>
	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>
			<td><img src="@item.ImageUrl" style="height:75px;width:75px" /></td>
			<td>@item.CourseName</td>
			<td>@item.Price $</td>
			<td>@item.CourseCategory.Name</td>
			<td>@(item.IsShown ? "Shown" : "Not Shown")</td>
			<td>
				<button onclick="deleteCourse(@item.CourseId)" class="btn btn-outline-danger">Delete </button>
				<a asp-action="UpdateCourse" asp-controller="Course" asp-area="Admin" asp-route-id="@item.CourseId" class="btn btn-outline-info">Update</a>
			</td>
			<td>
				<a asp-action="ShowOnMainPage" asp-controller="Course" asp-area="Admin" asp-route-id="@item.CourseId" class="btn btn-outline-success">@(item.IsShown ? "Don't Show" : "Show") </a>
			</td>
		</tr>

	}
</table>
<br />

<a asp-action="CreateCourse" asp-controller="Course" asp-area="Admin" class="btn btn-outline-primary">Create New Course</a>

<script>


	function deleteCourse(id) {


		Swal.fire({
			title: "Are you sure?",
			text: "You won't be able to revert this!",
			icon: "warning",
			showCancelButton: true,
			confirmButtonColor: "#3085d6",
			cancelButtonColor: "#d33",
			confirmButtonText: "Yes, delete it!",
			cancelButtonText: "Cancel"
		}).then((result) => {
			if (result.isConfirmed) {
				window.location.href = "/Admin/Course/DeleteCourse/" + id;
			}
		});

	}

</script>

OnlineEdu.WebUI/Areas/Admin/Views/Course/UpdateCourse.cshtml
@model UpdateCourseDto
@{
    ViewData["Title"] = "Update Course";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="CourseId"/>
    <label>ImageUrl</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Course Name</label>
    <input type="text" asp-for="CourseName" class="form-control" />
    <br />
    <label>Price</label>
    <input type="text" asp-for="Price" class="form-control" />
    <br />
    <label>Category</label>
    <select asp-for="CourseCategoryId" class="form-control" asp-items="@ViewBag.courseCategories">
        <option>Choose Category</option>
    </select>
    <br />
    <label>Show in main page?</label>
    <input type="checkbox" asp-for="IsShown" class="form-check" />
    <br />
    <button class="btn btn-outline-primary">Update</button>
    <button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>