OnlineEdu.WebUI/Areas/Admin/Controllers/BlogCategoryController.cs
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.AboutDtos;
using OnlineEdu.WebUI.DTOs.BlogCategoryDtos;
using OnlineEdu.WebUI.Helpers;
using OnlineEdu.WebUI.Validators;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("[area]/[controller]/[action]/{id?}")]
	public class BlogCategoryController : Controller
	{
		private readonly HttpClient _client = HttpClientInstance.CreateClient();

		public async Task<IActionResult> Index()
		{

			var values = await _client.GetFromJsonAsync<List<ResultBlogCategoryDto>>("blogcategories");
			return View(values);
		}

		public async Task<IActionResult> DeleteBlogCategory(int id)
		{
			await _client.DeleteAsync($"blogcategories/{id}");
			return RedirectToAction(nameof(Index));
		}

		public IActionResult CreateBlogCategory()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CreateBlogCategory(CreateBlogCategoryDto dto)
		{
			var validator = new BlogCategoryValidator();
			var validationResult = await validator.ValidateAsync(dto);
			if (!validationResult.IsValid)
			{
				ModelState.Clear();
				foreach(var ex in validationResult.Errors)
				{
					ModelState.AddModelError(ex.PropertyName,ex.ErrorMessage);
				}
				return View();
			}
			await _client.PostAsJsonAsync("blogcategories", dto);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> UpdateBlogCategory(int id)
		{
			var values = await _client.GetFromJsonAsync<UpdateBlogCategoryDto>($"blogcategories/{id}");
			return View(values);
		}

		[HttpPost]
		public async Task<IActionResult> UpdateBlogCategory(UpdateBlogCategoryDto dto)
		{
			var validator = new UpdateBlogCategoryValidator();
			var validationResult = await validator.ValidateAsync(dto);
			if (!validationResult.IsValid)
			{
				ModelState.Clear();
				foreach (var ex in validationResult.Errors)
				{
					ModelState.AddModelError(ex.PropertyName, ex.ErrorMessage);
				}
				return View();
			}
			await _client.PutAsJsonAsync("blogcategories", dto);
			return RedirectToAction(nameof(Index));
		}
	}
}

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/CreateBlogCategory.cshtml
@model CreateBlogCategoryDto
@{
    ViewData["Title"] = "Create Blog Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
	<label>Category Name</label>
	<input type="text" asp-for="Name" class="form-control" />
	<span asp-validation-for="Name" class="text-danger"></span>
	<br />
	<button class="btn btn-outline-primary">Save</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/Index.cshtml
@model List<ResultBlogCategoryDto>
@{
	ViewData["Title"] = "Blog Categories";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
	int count = 0;
}

<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>Category Name</th>

		<th></th>
	</tr>
	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>
			<td>@item.Name</td>
			<td>
				<button onclick="deleteBlogCategory(@item.BlogCategoryId)" class="btn btn-outline-danger">Delete </button>
				<a asp-action="UpdateBlogCategory" asp-controller="BlogCategory" asp-area="Admin" asp-route-id="@item.BlogCategoryId" class="btn btn-outline-info">Update</a>
			</td>
		</tr>

	}
</table>
<br />

<a asp-action="CreateBlogCategory" asp-controller="BlogCategory" asp-area="Admin" class="btn btn-outline-primary">Create New BlogCategory</a>

<script>


	function deleteBlogCategory(id) {


		Swal.fire({
			title: "Are you sure?",
			text: "You won't be able to revert this!",
			icon: "warning",
			showCancelButton: true,
			confirmButtonColor: "#3085d6",
			cancelButtonColor: "#d33",
			confirmButtonText: "Yes, delete it!",
			cancelButtonText: "Cancel"
		}).then((result) => {
			if (result.isConfirmed) {
				window.location.href = "/Admin/BlogCategory/DeleteBlogCategory/" + id; 
			}
		});

	}

</script>

OnlineEdu.WebUI/Areas/Admin/Views/BlogCategory/UpdateBlogCategory.cshtml
@model UpdateBlogCategoryDto
@{
    ViewData["Title"] = "Update Blog Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
	<input type="hidden" asp-for="BlogCategoryId" />
	<label>Category Name</label>
	<input type="text" asp-for="Name" class="form-control" />
	<span asp-validation-for="Name" class="text-danger"></span>
	<br />
	<button class="btn btn-outline-primary">Save</button>
	<button class="btn btn-outline-danger" asp-action="Index">Cancel</button>
</form>